<a href="https://colab.research.google.com/github/007-athul/DSA-case-study1/blob/main/numpyactivity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import numpy as np

1. Create a NumPy array with values from 10 to 49 (inclusive).
● Reshape it into a 4x10 matrix.
● Then extract the last column from the reshaped matrix

In [25]:
a=np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [26]:
reshaped=a.reshape(4,10)
reshaped

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [27]:
last_col= reshaped[:-1]
last_col

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

Create two 3×3 matrices:
One filled with all 5s , One with values from 1 to 9
● Add the two matrices
● Multiply them element-wise
● Then find the transpose of the result

In [28]:
A=np.full((3,3),5)
B=np.arange(1,10).reshape(3,3)

A,B

(array([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]),
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]))

In [29]:
sum= A+B
print(f"Result of Addition:\n {sum}")


Result of Addition:
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [30]:
multiply=A*B
print(f"Result of Multiplication:\n {multiply}")


Result of Multiplication:
 [[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [31]:
#transpose of multiplied matrix
multiply.T

array([[ 5, 20, 35],
       [10, 25, 40],
       [15, 30, 45]])

Create a NumPy array of 15 random integers between 10 and 100. ● Replace all values greater than 50 with -1 ● Count how many values were replaced.

In [32]:
C= np.random.randint(10,101,15)
print(f"original :{C}")

count= np.sum(C>50)
C[C>50] = -1
print(f"\nModified Array:\n{C}")
print("\nNumber of values replaced:", count)


original :[40 17 78 90 46 95 52 36 31 88 85 43 25 29 88]

Modified Array:
[40 17 -1 -1 46 -1 -1 36 31 -1 -1 43 25 29 -1]

Number of values replaced: 7


Generate a 5×4 array with random values between 0 and 1 (float).
● Find the row with the maximum sum of values.
● Normalize each row using the formula:

In [33]:
D=np.random.randint(0,2,20).reshape(5,4)
D

array([[0, 0, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 1, 1],
       [1, 0, 0, 0],
       [1, 1, 0, 0]])

In [34]:
#maximum row sum
row_sum= D.sum(axis=1)
max_row_val=np.argmax(row_sum)

print(f"Row with maximum Sum index position: {max_row_val}  ")



Row with maximum Sum index position: 2  


In [35]:
#normalize each row
row_min = D.min(axis=1, keepdims=True)
row_max = D.max(axis=1, keepdims=True)

normalized = (D - row_min) / (row_max - row_min)

print("\nNormalized Array:")
print(normalized)


Normalized Array:
[[0. 0. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 1. 1.]
 [1. 0. 0. 0.]
 [1. 1. 0. 0.]]


arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
● Find all unique elements
● Find the duplicates (elements that appear more than once)

In [36]:
arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
#unique value printing
unique=np.unique(arr)
unique

array([1, 3, 5, 7, 9])

In [37]:
#duplicates value
values, counts = np.unique(arr, return_counts=True)
duplicates = values[counts > 1]



print("\nDuplicate Elements:")
print(duplicates)


Duplicate Elements:
[1 3 5]


6. Create a 6×6 NumPy array with values from 1 to 36.
● Extract the middle 4×4 submatrix.
● Then extract all even numbers from this submatrix.

In [38]:
arr = np.arange(1, 37).reshape(6, 6)
middle = arr[1:5, 1:5]
even_numbers = middle[middle % 2 == 0]
print("Original Array:")
print(arr)
print("\nMiddle 4x4 Submatrix:")
print(middle)
print("\nEven Numbers:")
print(even_numbers)

Original Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Middle 4x4 Submatrix:
[[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]

Even Numbers:
[ 8 10 14 16 20 22 26 28]


7. Generate an array of shape (3, 4) with values from 0 to 11.
● Reshape it to (2, 6)
● Then flatten it into a 1D array
● Convert the 1D array back to shape (4, 3)

In [39]:
arr = np.arange(12).reshape(3, 4)
reshaped = arr.reshape(2, 6)
flattened = reshaped.flatten()
final_array = flattened.reshape(4, 3)
print("Original Array:")
print(arr)
print("\nReshaped to (2,6):")
print(reshaped)
print("\nFlattened Array:")
print(flattened)
print("\nReshaped to (4,3):")
print(final_array)

Original Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped to (2,6):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Flattened Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped to (4,3):
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


8 . Create an array: a = np.array([[1, 2], [3, 4]])
● Append a new row [5, 6]
● Then append a new column [7, 8, 9]

In [40]:
a = np.array([[1, 2],
              [3, 4]])
# row Append
a = np.append(a, [[5, 6]], axis=0)
# column append
a = np.append(a, [[7], [8], [9]], axis=1)
print(a)

[[1 2 7]
 [3 4 8]
 [5 6 9]]


9.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
● Join them into a single array
● Reshape the result into a 3×3 matrix
● Extract the diagonal elements

In [41]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
joined = np.concatenate((a, b, c))
matrix = joined.reshape(3, 3)
diagonal = np.diag(matrix)
print("Joined Array:")
print(joined)
print("\n3x3 Matrix:")
print(matrix)
print("\nDiagonal Elements:")
print(diagonal)

Joined Array:
[1 2 3 4 5 6 7 8 9]

3x3 Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Diagonal Elements:
[1 5 9]


10. Create a NumPy array of integers from 1 to 20.
● Extract all values that are divisible by 3 or 5.
● Count how many such values exist.

In [42]:
arr = np.arange(1, 21)
result = arr[(arr % 3 == 0) | (arr % 5 == 0)]
count = len(result)
print("Numbers divisible by 3 or 5:")
print(result)
print("\nCount:")
print(count)

Numbers divisible by 3 or 5:
[ 3  5  6  9 10 12 15 18 20]

Count:
9
